version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "00:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - nlmenke
  labels:
  - dependencies
